const sobresPokemon = [
  {
    id: 1,
    nombre: "Espada y Escudo - Oscuridad Incandescente",
    img: "https://example.com/oscuridad-incandescente.jpg",
    descripcion: "Descubre increíbles cartas de tipo Fuego y Dragón en este set de la serie Espada y Escudo.",
    precio: 120.99,
    expansion: "Espada y Escudo",
  },
  {
    id: 2,
    nombre: "Espada y Escudo - Reino Escalofriante",
    img: "https://example.com/reino-escalofriante.jpg",
    descripcion: "Prepárate para el invierno con cartas inspiradas en Pokémon tipo Hielo y Fantasma.",
    precio: 110.50,
    expansion: "Espada y Escudo",
  },
  {
    id: 3,
    nombre: "Espada y Escudo - Cielos Evolutivos",
    img: "https://example.com/cielos-evolutivos.jpg",
    descripcion: "Un set que destaca a las evoluciones de Eevee y otros Pokémon voladores.",
    precio: 130.75,
    expansion: "Espada y Escudo",
  },
  {
    id: 4,
    nombre: "Espada y Escudo - Celebraciones",
    img: "https://example.com/celebraciones.jpg",
    descripcion: "Celebra 25 años de Pokémon con cartas icónicas y nuevas versiones de tus favoritos.",
    precio: 150.00,
    expansion: "Espada y Escudo",
  },
  {
    id: 5,
    nombre: "Espada y Escudo - Estilo de Combate",
    img: "https://example.com/estilo-de-combate.jpg",
    descripcion: "Domina el campo de batalla con nuevas mecánicas de combate Rápido y Golpe Brusco.",
    precio: 125.49,
    expansion: "Espada y Escudo",
  },
  {
    id: 6,
    nombre: "XY - Destinos Brillantes",
    img: "https://example.com/destinos-brillantes.jpg",
    descripcion: "Captura Pokémon brillantes en este set lleno de cartas raras y coleccionables.",
    precio: 140.20,
    expansion: "XY",
  },
  {
    id: 7,
    nombre: "XY - Fuerza Fantasma",
    img: "https://example.com/fuerza-fantasma.jpg",
    descripcion: "Explora lo sobrenatural con cartas de tipo Fantasma y Oscuro llenas de sorpresas.",
    precio: 135.00,
    expansion: "XY",
  },
  {
    id: 8,
    nombre: "XY - Orígenes Antiguos",
    img: "https://example.com/origenes-antiguos.jpg",
    descripcion: "Regresa al pasado con Pokémon legendarios y cartas con arte único en este emocionante set.",
    precio: 145.60,
    expansion: "XY",
  },
  {
    id: 9,
    nombre: "Sol y Luna - Eclipse Cósmico",
    img: "https://example.com/eclipse-cosmico.jpg",
    descripcion: "Un paquete que combina Pokémon y sus aliados para un estilo de combate único y emocionante.",
    precio: 138.00,
    expansion: "Sol y Luna",
  },
  {
    id: 10,
    nombre: "Sol y Luna - Guardianes Ascendentes",
    img: "https://example.com/guardianes-ascendentes.jpg",
    descripcion: "Descubre Pokémon guardianes legendarios en este emocionante paquete de expansión.",
    precio: 129.99,
    expansion: "Sol y Luna",
  },
];

export default sobresPokemon;